version: '3.5'
services:
  vue:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"